version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=crud
      - POSTGRES_USER=pas
      - POSTGRES_PASSWORD=pas
    volumes:
      - db:/var/lib/dbase/crud
    ports:
      - "5441:5432"

volumes:
  db: